### ISSUE TITLE
Function request, find all files in a specific directory, and then select Safetensors file

### ISSUE THREAD

**Issue by hahajaja** [by321/safetensors_util#1]
You don't have to move the file and enter a file name

**Comment by by321** [comment]
Not sure what you mean, can you explain more ?

**Comment by hahajaja** [comment]
Thank you for your reply. I found a simpler way to change the suffix to TXT without typing a long list of instructions

**Comment by hahajaja** [comment]
@by321 
I am porting a UI for this project ,can help me
 reproducing the "-PM" function ?
![20230602165151](https://github.com/by321/safetensors_util/assets/23209894/ce086838-2d67-47e9-889b-90ac8c628b61)
[safetensors_util.zip](https://github.com/by321/safetensors_util/files/11633742/safetensors_util.zip)

**Comment by by321** [comment]
Where can I download that file ?

**Comment by hahajaja** [comment]
![QQ图片20230603005024](https://github.com/by321/safetensors_util/assets/23209894/becb4322-199b-4fd4-8579-c6bbadf1f57d)

here

**Comment by by321** [comment]
I thought you have a LoRA files that can't be displayed correctly. You just need to call "_ParseMore(md)" after parsing the header.

**Comment by hahajaja** [comment]
Thank
